### PR TITLE
move item definitions to a JSON file

### PR DESCRIPTION
**Pull request by kungtotte**
Instead of hardcoding every item in the code it's easier to define
them in a separate JSON file, this way you can quickly add items
or change existing ones without digging through code, and the code
becomes easier to read in the process.

### CODE REVIEW

**Comment by sgtlaggy** [comment]
Please add an `import json` line so this can be merged properly.

**Comment by dis446** [comment]
Great idea. Will merge.

**Comment by dis446** [comment]
Could I also make a request? There is a list in the main game loop called all_items. It is used to check if an item actually exists. E.g. if player types in 'craft money' it would be False. 
Instead of that, could  you make a boolean function, with one string argument, that checks the JSON file and returns True, if the item exists. This would  also remove the need for the global all_items list. I would do it myself but i don't know what JSON or 'parsing' even is :/

**Comment by kungtotte** [comment]
Sure I can do that. 

Also there's a lot of work to be done with pep8 still, so I can start there and then move on to the JSON stuff.

JSON stands for JavaScript Object Notation and it's just a handy way to describe data and easily load it into your program (or write to it, for save files etc.), and that's what parsing means in this context: taking the JSON string and turning it into Python data structures.

**Comment by sgtlaggy** [comment]
@kungtotte I'll be working on PEP8 compliance today. Just had to go to bed early last night.

**Pull request merged**
